services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: app
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - .:/var/www/html

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    
  blender:
      image: linuxserver/blender:5.2.0
      container_name: blender
      restart: always
      group_add:
        - "3000"  
      environment:
        - PIXELFLUX_WAYLAND=true
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
      ports:
        - 3000:3000
        - 3001:3001
        - "5000:5000"
      volumes:
        - ./assets:/assets
        - ./blender_scripts:/scripts
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
volumes:
  postgres_data: