# Generated by Django 6.0.6 on 2026-08-16 19:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_url', models.CharField(blank=True, null=True)),
                ('banner_url', models.CharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_label', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(blank=True, null=True)),
                ('object_category', models.CharField(blank=True, null=True)),
                ('style', models.CharField(blank=True, null=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
                ('vertices', models.IntegerField(null=True)),
                ('faces', models.IntegerField(null=True)),
                ('edges', models.IntegerField(null=True)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=6)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='models3d.model3d')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
