# Generated by Django 6.0.6 on 2026-06-28 12:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RenderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models3d/renders/')),
                ('angle', models.CharField(blank=True, help_text='e.g. front, side, top', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models3d/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_label', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('vertices', models.IntegerField(null=True)),
                ('faces', models.IntegerField(null=True)),
                ('edges', models.IntegerField(null=True)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=6)),
                ('surface_area', models.FloatField(null=True)),
                ('volume_estimate', models.FloatField(null=True)),
                ('is_manifold', models.BooleanField(null=True)),
                ('holes_count', models.IntegerField(null=True)),
                ('connected_components', models.IntegerField(null=True)),
                ('symmetry_axis', models.CharField(blank=True, max_length=10, null=True)),
                ('compactness', models.FloatField(null=True)),
                ('elongation', models.FloatField(null=True)),
                ('curvature_mean', models.FloatField(null=True)),
                ('center_of_mass', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=3)),
                ('stability_score', models.FloatField(null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='models3d.category')),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
