# Generated by Django 6.0.6 on 2026-08-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='surface_area',
        ),
    ]
